//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAround.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDatHangs = new HashSet<ChiTietDatHang>();
        }
    
        public int MaSanPham { get; set; }
        public int NhomSanPhamID { get; set; }
        public string TenSanPham { get; set; }
        public int DonGia { get; set; }
        public string Hinh { get; set; }
        public string BiDanh { get; set; }
        public string ndTomTat { get; set; }
        public string ndDayDu { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public string tkThanhVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHang> ChiTietDatHangs { get; set; }
        public virtual NhomSanPham NhomSanPham { get; set; }
        public virtual QuanTri QuanTri { get; set; }
    }
}
